from package.base import *
from package.load import *
from package.login import *
from package.cariwahana import *
from package.usetiket import *
from package.addwahana import *
from package.kehilangan import *
from package.bestwahana import *
from package.upgradegold import *
